[package]
name = "perf-event"
description = "A Rust interface to Linux performance monitoring"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Jim Blandy <jimb@red-bean.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
libc = "0.2"

[build-dependencies]
bindgen = "0.52"
